apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: test
spec:
  ports:
    - port: 3306
      name: mysql
      protocol: TCP
      targetPort: 3306
      nodePort: 30250
  selector:
    app: mysql
  type: NodePort
---
  apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app:
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: hjj123456
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-dev-conf
              mountPath: /etc/mysql

      volumes:
        - name: mysql-data
          nfs:
            server: 10.0.19.129  #nfs的ip地址
            path: /opt/data/mysql/data
        - name: mysql-dev-conf
          nfs:
            server: 10.0.19.129
            name: /opt/data/mysql/cnf

