// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Base.proto

package com.ycw.grpc;

public final class BaseProto {
  private BaseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PropItemProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PropItemProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nBase.proto\"6\n\rPropItemProto\022\026\n\016itemCon" +
      "figType\030\001 \001(\003\022\r\n\005value\030\002 \001(\tB\033\n\014com.ycw." +
      "grpcB\tBaseProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PropItemProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PropItemProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PropItemProto_descriptor,
        new java.lang.String[] { "ItemConfigType", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
