// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mailbox.proto

package com.ycw.grpc;

public interface CollectRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CollectRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mailboxId = 1;</code>
   * @return The mailboxId.
   */
  java.lang.String getMailboxId();
  /**
   * <code>string mailboxId = 1;</code>
   * @return The bytes for mailboxId.
   */
  com.google.protobuf.ByteString
      getMailboxIdBytes();
}
