// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mailbox.proto

package com.ycw.grpc;

public interface CollectResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CollectResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 collectSuccess = 1;</code>
   * @return The collectSuccess.
   */
  long getCollectSuccess();
}
