// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mailbox.proto

package com.ycw.grpc;

/**
 * Protobuf type {@code MailboxProto}
 */
public final class MailboxProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MailboxProto)
    MailboxProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MailboxProto.newBuilder() to construct.
  private MailboxProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MailboxProto() {
    mailboxId_ = "";
    title_ = "";
    body_ = "";
    appendix_ = "";
    mailTypeDescription_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MailboxProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MailboxProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            mailboxId_ = s;
            break;
          }
          case 16: {

            userId_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            body_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            appendix_ = s;
            break;
          }
          case 48: {

            mailType_ = input.readInt64();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            mailTypeDescription_ = s;
            break;
          }
          case 64: {

            collectAt_ = input.readInt64();
            break;
          }
          case 72: {

            expiredAt_ = input.readInt64();
            break;
          }
          case 80: {

            createAt_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ycw.grpc.Mailbox.internal_static_MailboxProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ycw.grpc.Mailbox.internal_static_MailboxProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ycw.grpc.MailboxProto.class, com.ycw.grpc.MailboxProto.Builder.class);
  }

  public static final int MAILBOXID_FIELD_NUMBER = 1;
  private volatile java.lang.Object mailboxId_;
  /**
   * <code>string mailboxId = 1;</code>
   * @return The mailboxId.
   */
  @java.lang.Override
  public java.lang.String getMailboxId() {
    java.lang.Object ref = mailboxId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mailboxId_ = s;
      return s;
    }
  }
  /**
   * <code>string mailboxId = 1;</code>
   * @return The bytes for mailboxId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMailboxIdBytes() {
    java.lang.Object ref = mailboxId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mailboxId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERID_FIELD_NUMBER = 2;
  private long userId_;
  /**
   * <code>int64 userId = 2;</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int TITLE_FIELD_NUMBER = 3;
  private volatile java.lang.Object title_;
  /**
   * <code>string title = 3;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 3;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BODY_FIELD_NUMBER = 4;
  private volatile java.lang.Object body_;
  /**
   * <code>string body = 4;</code>
   * @return The body.
   */
  @java.lang.Override
  public java.lang.String getBody() {
    java.lang.Object ref = body_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      body_ = s;
      return s;
    }
  }
  /**
   * <code>string body = 4;</code>
   * @return The bytes for body.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBodyBytes() {
    java.lang.Object ref = body_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      body_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPENDIX_FIELD_NUMBER = 5;
  private volatile java.lang.Object appendix_;
  /**
   * <code>string appendix = 5;</code>
   * @return The appendix.
   */
  @java.lang.Override
  public java.lang.String getAppendix() {
    java.lang.Object ref = appendix_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appendix_ = s;
      return s;
    }
  }
  /**
   * <code>string appendix = 5;</code>
   * @return The bytes for appendix.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppendixBytes() {
    java.lang.Object ref = appendix_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appendix_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAILTYPE_FIELD_NUMBER = 6;
  private long mailType_;
  /**
   * <code>int64 mailType = 6;</code>
   * @return The mailType.
   */
  @java.lang.Override
  public long getMailType() {
    return mailType_;
  }

  public static final int MAILTYPEDESCRIPTION_FIELD_NUMBER = 7;
  private volatile java.lang.Object mailTypeDescription_;
  /**
   * <code>string mailTypeDescription = 7;</code>
   * @return The mailTypeDescription.
   */
  @java.lang.Override
  public java.lang.String getMailTypeDescription() {
    java.lang.Object ref = mailTypeDescription_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mailTypeDescription_ = s;
      return s;
    }
  }
  /**
   * <code>string mailTypeDescription = 7;</code>
   * @return The bytes for mailTypeDescription.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMailTypeDescriptionBytes() {
    java.lang.Object ref = mailTypeDescription_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mailTypeDescription_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLLECTAT_FIELD_NUMBER = 8;
  private long collectAt_;
  /**
   * <code>int64 collectAt = 8;</code>
   * @return The collectAt.
   */
  @java.lang.Override
  public long getCollectAt() {
    return collectAt_;
  }

  public static final int EXPIREDAT_FIELD_NUMBER = 9;
  private long expiredAt_;
  /**
   * <code>int64 expiredAt = 9;</code>
   * @return The expiredAt.
   */
  @java.lang.Override
  public long getExpiredAt() {
    return expiredAt_;
  }

  public static final int CREATEAT_FIELD_NUMBER = 10;
  private long createAt_;
  /**
   * <code>int64 createAt = 10;</code>
   * @return The createAt.
   */
  @java.lang.Override
  public long getCreateAt() {
    return createAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mailboxId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mailboxId_);
    }
    if (userId_ != 0L) {
      output.writeInt64(2, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(body_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, body_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appendix_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, appendix_);
    }
    if (mailType_ != 0L) {
      output.writeInt64(6, mailType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mailTypeDescription_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, mailTypeDescription_);
    }
    if (collectAt_ != 0L) {
      output.writeInt64(8, collectAt_);
    }
    if (expiredAt_ != 0L) {
      output.writeInt64(9, expiredAt_);
    }
    if (createAt_ != 0L) {
      output.writeInt64(10, createAt_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mailboxId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mailboxId_);
    }
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(body_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, body_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appendix_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, appendix_);
    }
    if (mailType_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, mailType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mailTypeDescription_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, mailTypeDescription_);
    }
    if (collectAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, collectAt_);
    }
    if (expiredAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, expiredAt_);
    }
    if (createAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, createAt_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ycw.grpc.MailboxProto)) {
      return super.equals(obj);
    }
    com.ycw.grpc.MailboxProto other = (com.ycw.grpc.MailboxProto) obj;

    if (!getMailboxId()
        .equals(other.getMailboxId())) return false;
    if (getUserId()
        != other.getUserId()) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getBody()
        .equals(other.getBody())) return false;
    if (!getAppendix()
        .equals(other.getAppendix())) return false;
    if (getMailType()
        != other.getMailType()) return false;
    if (!getMailTypeDescription()
        .equals(other.getMailTypeDescription())) return false;
    if (getCollectAt()
        != other.getCollectAt()) return false;
    if (getExpiredAt()
        != other.getExpiredAt()) return false;
    if (getCreateAt()
        != other.getCreateAt()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MAILBOXID_FIELD_NUMBER;
    hash = (53 * hash) + getMailboxId().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + BODY_FIELD_NUMBER;
    hash = (53 * hash) + getBody().hashCode();
    hash = (37 * hash) + APPENDIX_FIELD_NUMBER;
    hash = (53 * hash) + getAppendix().hashCode();
    hash = (37 * hash) + MAILTYPE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMailType());
    hash = (37 * hash) + MAILTYPEDESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getMailTypeDescription().hashCode();
    hash = (37 * hash) + COLLECTAT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCollectAt());
    hash = (37 * hash) + EXPIREDAT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExpiredAt());
    hash = (37 * hash) + CREATEAT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreateAt());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ycw.grpc.MailboxProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ycw.grpc.MailboxProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ycw.grpc.MailboxProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ycw.grpc.MailboxProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ycw.grpc.MailboxProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ycw.grpc.MailboxProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ycw.grpc.MailboxProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ycw.grpc.MailboxProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ycw.grpc.MailboxProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ycw.grpc.MailboxProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ycw.grpc.MailboxProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ycw.grpc.MailboxProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ycw.grpc.MailboxProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MailboxProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MailboxProto)
      com.ycw.grpc.MailboxProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ycw.grpc.Mailbox.internal_static_MailboxProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ycw.grpc.Mailbox.internal_static_MailboxProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ycw.grpc.MailboxProto.class, com.ycw.grpc.MailboxProto.Builder.class);
    }

    // Construct using com.ycw.grpc.MailboxProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      mailboxId_ = "";

      userId_ = 0L;

      title_ = "";

      body_ = "";

      appendix_ = "";

      mailType_ = 0L;

      mailTypeDescription_ = "";

      collectAt_ = 0L;

      expiredAt_ = 0L;

      createAt_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ycw.grpc.Mailbox.internal_static_MailboxProto_descriptor;
    }

    @java.lang.Override
    public com.ycw.grpc.MailboxProto getDefaultInstanceForType() {
      return com.ycw.grpc.MailboxProto.getDefaultInstance();
    }

    @java.lang.Override
    public com.ycw.grpc.MailboxProto build() {
      com.ycw.grpc.MailboxProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ycw.grpc.MailboxProto buildPartial() {
      com.ycw.grpc.MailboxProto result = new com.ycw.grpc.MailboxProto(this);
      result.mailboxId_ = mailboxId_;
      result.userId_ = userId_;
      result.title_ = title_;
      result.body_ = body_;
      result.appendix_ = appendix_;
      result.mailType_ = mailType_;
      result.mailTypeDescription_ = mailTypeDescription_;
      result.collectAt_ = collectAt_;
      result.expiredAt_ = expiredAt_;
      result.createAt_ = createAt_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ycw.grpc.MailboxProto) {
        return mergeFrom((com.ycw.grpc.MailboxProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ycw.grpc.MailboxProto other) {
      if (other == com.ycw.grpc.MailboxProto.getDefaultInstance()) return this;
      if (!other.getMailboxId().isEmpty()) {
        mailboxId_ = other.mailboxId_;
        onChanged();
      }
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (!other.getBody().isEmpty()) {
        body_ = other.body_;
        onChanged();
      }
      if (!other.getAppendix().isEmpty()) {
        appendix_ = other.appendix_;
        onChanged();
      }
      if (other.getMailType() != 0L) {
        setMailType(other.getMailType());
      }
      if (!other.getMailTypeDescription().isEmpty()) {
        mailTypeDescription_ = other.mailTypeDescription_;
        onChanged();
      }
      if (other.getCollectAt() != 0L) {
        setCollectAt(other.getCollectAt());
      }
      if (other.getExpiredAt() != 0L) {
        setExpiredAt(other.getExpiredAt());
      }
      if (other.getCreateAt() != 0L) {
        setCreateAt(other.getCreateAt());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ycw.grpc.MailboxProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ycw.grpc.MailboxProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object mailboxId_ = "";
    /**
     * <code>string mailboxId = 1;</code>
     * @return The mailboxId.
     */
    public java.lang.String getMailboxId() {
      java.lang.Object ref = mailboxId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mailboxId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mailboxId = 1;</code>
     * @return The bytes for mailboxId.
     */
    public com.google.protobuf.ByteString
        getMailboxIdBytes() {
      java.lang.Object ref = mailboxId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mailboxId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mailboxId = 1;</code>
     * @param value The mailboxId to set.
     * @return This builder for chaining.
     */
    public Builder setMailboxId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mailboxId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mailboxId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMailboxId() {
      
      mailboxId_ = getDefaultInstance().getMailboxId();
      onChanged();
      return this;
    }
    /**
     * <code>string mailboxId = 1;</code>
     * @param value The bytes for mailboxId to set.
     * @return This builder for chaining.
     */
    public Builder setMailboxIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mailboxId_ = value;
      onChanged();
      return this;
    }

    private long userId_ ;
    /**
     * <code>int64 userId = 2;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>int64 userId = 2;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 userId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 3;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 3;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 3;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string title = 3;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object body_ = "";
    /**
     * <code>string body = 4;</code>
     * @return The body.
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string body = 4;</code>
     * @return The bytes for body.
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string body = 4;</code>
     * @param value The body to set.
     * @return This builder for chaining.
     */
    public Builder setBody(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string body = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBody() {
      
      body_ = getDefaultInstance().getBody();
      onChanged();
      return this;
    }
    /**
     * <code>string body = 4;</code>
     * @param value The bytes for body to set.
     * @return This builder for chaining.
     */
    public Builder setBodyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      body_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object appendix_ = "";
    /**
     * <code>string appendix = 5;</code>
     * @return The appendix.
     */
    public java.lang.String getAppendix() {
      java.lang.Object ref = appendix_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appendix_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string appendix = 5;</code>
     * @return The bytes for appendix.
     */
    public com.google.protobuf.ByteString
        getAppendixBytes() {
      java.lang.Object ref = appendix_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appendix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string appendix = 5;</code>
     * @param value The appendix to set.
     * @return This builder for chaining.
     */
    public Builder setAppendix(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      appendix_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string appendix = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppendix() {
      
      appendix_ = getDefaultInstance().getAppendix();
      onChanged();
      return this;
    }
    /**
     * <code>string appendix = 5;</code>
     * @param value The bytes for appendix to set.
     * @return This builder for chaining.
     */
    public Builder setAppendixBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      appendix_ = value;
      onChanged();
      return this;
    }

    private long mailType_ ;
    /**
     * <code>int64 mailType = 6;</code>
     * @return The mailType.
     */
    @java.lang.Override
    public long getMailType() {
      return mailType_;
    }
    /**
     * <code>int64 mailType = 6;</code>
     * @param value The mailType to set.
     * @return This builder for chaining.
     */
    public Builder setMailType(long value) {
      
      mailType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 mailType = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMailType() {
      
      mailType_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object mailTypeDescription_ = "";
    /**
     * <code>string mailTypeDescription = 7;</code>
     * @return The mailTypeDescription.
     */
    public java.lang.String getMailTypeDescription() {
      java.lang.Object ref = mailTypeDescription_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mailTypeDescription_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mailTypeDescription = 7;</code>
     * @return The bytes for mailTypeDescription.
     */
    public com.google.protobuf.ByteString
        getMailTypeDescriptionBytes() {
      java.lang.Object ref = mailTypeDescription_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mailTypeDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mailTypeDescription = 7;</code>
     * @param value The mailTypeDescription to set.
     * @return This builder for chaining.
     */
    public Builder setMailTypeDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mailTypeDescription_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mailTypeDescription = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearMailTypeDescription() {
      
      mailTypeDescription_ = getDefaultInstance().getMailTypeDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string mailTypeDescription = 7;</code>
     * @param value The bytes for mailTypeDescription to set.
     * @return This builder for chaining.
     */
    public Builder setMailTypeDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mailTypeDescription_ = value;
      onChanged();
      return this;
    }

    private long collectAt_ ;
    /**
     * <code>int64 collectAt = 8;</code>
     * @return The collectAt.
     */
    @java.lang.Override
    public long getCollectAt() {
      return collectAt_;
    }
    /**
     * <code>int64 collectAt = 8;</code>
     * @param value The collectAt to set.
     * @return This builder for chaining.
     */
    public Builder setCollectAt(long value) {
      
      collectAt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 collectAt = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearCollectAt() {
      
      collectAt_ = 0L;
      onChanged();
      return this;
    }

    private long expiredAt_ ;
    /**
     * <code>int64 expiredAt = 9;</code>
     * @return The expiredAt.
     */
    @java.lang.Override
    public long getExpiredAt() {
      return expiredAt_;
    }
    /**
     * <code>int64 expiredAt = 9;</code>
     * @param value The expiredAt to set.
     * @return This builder for chaining.
     */
    public Builder setExpiredAt(long value) {
      
      expiredAt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 expiredAt = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearExpiredAt() {
      
      expiredAt_ = 0L;
      onChanged();
      return this;
    }

    private long createAt_ ;
    /**
     * <code>int64 createAt = 10;</code>
     * @return The createAt.
     */
    @java.lang.Override
    public long getCreateAt() {
      return createAt_;
    }
    /**
     * <code>int64 createAt = 10;</code>
     * @param value The createAt to set.
     * @return This builder for chaining.
     */
    public Builder setCreateAt(long value) {
      
      createAt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 createAt = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreateAt() {
      
      createAt_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MailboxProto)
  }

  // @@protoc_insertion_point(class_scope:MailboxProto)
  private static final com.ycw.grpc.MailboxProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ycw.grpc.MailboxProto();
  }

  public static com.ycw.grpc.MailboxProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MailboxProto>
      PARSER = new com.google.protobuf.AbstractParser<MailboxProto>() {
    @java.lang.Override
    public MailboxProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MailboxProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MailboxProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MailboxProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ycw.grpc.MailboxProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

