// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mailbox.proto

package com.ycw.grpc;

public interface MailboxProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MailboxProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mailboxId = 1;</code>
   * @return The mailboxId.
   */
  java.lang.String getMailboxId();
  /**
   * <code>string mailboxId = 1;</code>
   * @return The bytes for mailboxId.
   */
  com.google.protobuf.ByteString
      getMailboxIdBytes();

  /**
   * <code>int64 userId = 2;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>string title = 3;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 3;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string body = 4;</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <code>string body = 4;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();

  /**
   * <code>string appendix = 5;</code>
   * @return The appendix.
   */
  java.lang.String getAppendix();
  /**
   * <code>string appendix = 5;</code>
   * @return The bytes for appendix.
   */
  com.google.protobuf.ByteString
      getAppendixBytes();

  /**
   * <code>int64 mailType = 6;</code>
   * @return The mailType.
   */
  long getMailType();

  /**
   * <code>string mailTypeDescription = 7;</code>
   * @return The mailTypeDescription.
   */
  java.lang.String getMailTypeDescription();
  /**
   * <code>string mailTypeDescription = 7;</code>
   * @return The bytes for mailTypeDescription.
   */
  com.google.protobuf.ByteString
      getMailTypeDescriptionBytes();

  /**
   * <code>int64 collectAt = 8;</code>
   * @return The collectAt.
   */
  long getCollectAt();

  /**
   * <code>int64 expiredAt = 9;</code>
   * @return The expiredAt.
   */
  long getExpiredAt();

  /**
   * <code>int64 createAt = 10;</code>
   * @return The createAt.
   */
  long getCreateAt();
}
