// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Base.proto

package com.ycw.grpc;

public interface PropItemProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PropItemProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 道具类型
   * </pre>
   *
   * <code>int64 itemConfigType = 1;</code>
   * @return The itemConfigType.
   */
  long getItemConfigType();

  /**
   * <pre>
   * 数值
   * </pre>
   *
   * <code>string value = 2;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <pre>
   * 数值
   * </pre>
   *
   * <code>string value = 2;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
