// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mailbox.proto

package com.ycw.grpc;

/**
 * Protobuf type {@code SendRequest}
 */
public final class SendRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SendRequest)
    SendRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SendRequest.newBuilder() to construct.
  private SendRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SendRequest() {
    mailboxProto_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SendRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SendRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              mailboxProto_ = new java.util.ArrayList<com.ycw.grpc.MailboxProto>();
              mutable_bitField0_ |= 0x00000001;
            }
            mailboxProto_.add(
                input.readMessage(com.ycw.grpc.MailboxProto.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        mailboxProto_ = java.util.Collections.unmodifiableList(mailboxProto_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ycw.grpc.Mailbox.internal_static_SendRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ycw.grpc.Mailbox.internal_static_SendRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ycw.grpc.SendRequest.class, com.ycw.grpc.SendRequest.Builder.class);
  }

  public static final int MAILBOXPROTO_FIELD_NUMBER = 1;
  private java.util.List<com.ycw.grpc.MailboxProto> mailboxProto_;
  /**
   * <code>repeated .MailboxProto mailboxProto = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.ycw.grpc.MailboxProto> getMailboxProtoList() {
    return mailboxProto_;
  }
  /**
   * <code>repeated .MailboxProto mailboxProto = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.ycw.grpc.MailboxProtoOrBuilder> 
      getMailboxProtoOrBuilderList() {
    return mailboxProto_;
  }
  /**
   * <code>repeated .MailboxProto mailboxProto = 1;</code>
   */
  @java.lang.Override
  public int getMailboxProtoCount() {
    return mailboxProto_.size();
  }
  /**
   * <code>repeated .MailboxProto mailboxProto = 1;</code>
   */
  @java.lang.Override
  public com.ycw.grpc.MailboxProto getMailboxProto(int index) {
    return mailboxProto_.get(index);
  }
  /**
   * <code>repeated .MailboxProto mailboxProto = 1;</code>
   */
  @java.lang.Override
  public com.ycw.grpc.MailboxProtoOrBuilder getMailboxProtoOrBuilder(
      int index) {
    return mailboxProto_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < mailboxProto_.size(); i++) {
      output.writeMessage(1, mailboxProto_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < mailboxProto_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, mailboxProto_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ycw.grpc.SendRequest)) {
      return super.equals(obj);
    }
    com.ycw.grpc.SendRequest other = (com.ycw.grpc.SendRequest) obj;

    if (!getMailboxProtoList()
        .equals(other.getMailboxProtoList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMailboxProtoCount() > 0) {
      hash = (37 * hash) + MAILBOXPROTO_FIELD_NUMBER;
      hash = (53 * hash) + getMailboxProtoList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ycw.grpc.SendRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ycw.grpc.SendRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ycw.grpc.SendRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ycw.grpc.SendRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ycw.grpc.SendRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ycw.grpc.SendRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ycw.grpc.SendRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ycw.grpc.SendRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ycw.grpc.SendRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ycw.grpc.SendRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ycw.grpc.SendRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ycw.grpc.SendRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ycw.grpc.SendRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SendRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SendRequest)
      com.ycw.grpc.SendRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ycw.grpc.Mailbox.internal_static_SendRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ycw.grpc.Mailbox.internal_static_SendRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ycw.grpc.SendRequest.class, com.ycw.grpc.SendRequest.Builder.class);
    }

    // Construct using com.ycw.grpc.SendRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMailboxProtoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (mailboxProtoBuilder_ == null) {
        mailboxProto_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        mailboxProtoBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ycw.grpc.Mailbox.internal_static_SendRequest_descriptor;
    }

    @java.lang.Override
    public com.ycw.grpc.SendRequest getDefaultInstanceForType() {
      return com.ycw.grpc.SendRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.ycw.grpc.SendRequest build() {
      com.ycw.grpc.SendRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ycw.grpc.SendRequest buildPartial() {
      com.ycw.grpc.SendRequest result = new com.ycw.grpc.SendRequest(this);
      int from_bitField0_ = bitField0_;
      if (mailboxProtoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          mailboxProto_ = java.util.Collections.unmodifiableList(mailboxProto_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.mailboxProto_ = mailboxProto_;
      } else {
        result.mailboxProto_ = mailboxProtoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ycw.grpc.SendRequest) {
        return mergeFrom((com.ycw.grpc.SendRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ycw.grpc.SendRequest other) {
      if (other == com.ycw.grpc.SendRequest.getDefaultInstance()) return this;
      if (mailboxProtoBuilder_ == null) {
        if (!other.mailboxProto_.isEmpty()) {
          if (mailboxProto_.isEmpty()) {
            mailboxProto_ = other.mailboxProto_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMailboxProtoIsMutable();
            mailboxProto_.addAll(other.mailboxProto_);
          }
          onChanged();
        }
      } else {
        if (!other.mailboxProto_.isEmpty()) {
          if (mailboxProtoBuilder_.isEmpty()) {
            mailboxProtoBuilder_.dispose();
            mailboxProtoBuilder_ = null;
            mailboxProto_ = other.mailboxProto_;
            bitField0_ = (bitField0_ & ~0x00000001);
            mailboxProtoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMailboxProtoFieldBuilder() : null;
          } else {
            mailboxProtoBuilder_.addAllMessages(other.mailboxProto_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ycw.grpc.SendRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ycw.grpc.SendRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.ycw.grpc.MailboxProto> mailboxProto_ =
      java.util.Collections.emptyList();
    private void ensureMailboxProtoIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        mailboxProto_ = new java.util.ArrayList<com.ycw.grpc.MailboxProto>(mailboxProto_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ycw.grpc.MailboxProto, com.ycw.grpc.MailboxProto.Builder, com.ycw.grpc.MailboxProtoOrBuilder> mailboxProtoBuilder_;

    /**
     * <code>repeated .MailboxProto mailboxProto = 1;</code>
     */
    public java.util.List<com.ycw.grpc.MailboxProto> getMailboxProtoList() {
      if (mailboxProtoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(mailboxProto_);
      } else {
        return mailboxProtoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .MailboxProto mailboxProto = 1;</code>
     */
    public int getMailboxProtoCount() {
      if (mailboxProtoBuilder_ == null) {
        return mailboxProto_.size();
      } else {
        return mailboxProtoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .MailboxProto mailboxProto = 1;</code>
     */
    public com.ycw.grpc.MailboxProto getMailboxProto(int index) {
      if (mailboxProtoBuilder_ == null) {
        return mailboxProto_.get(index);
      } else {
        return mailboxProtoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .MailboxProto mailboxProto = 1;</code>
     */
    public Builder setMailboxProto(
        int index, com.ycw.grpc.MailboxProto value) {
      if (mailboxProtoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMailboxProtoIsMutable();
        mailboxProto_.set(index, value);
        onChanged();
      } else {
        mailboxProtoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MailboxProto mailboxProto = 1;</code>
     */
    public Builder setMailboxProto(
        int index, com.ycw.grpc.MailboxProto.Builder builderForValue) {
      if (mailboxProtoBuilder_ == null) {
        ensureMailboxProtoIsMutable();
        mailboxProto_.set(index, builderForValue.build());
        onChanged();
      } else {
        mailboxProtoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MailboxProto mailboxProto = 1;</code>
     */
    public Builder addMailboxProto(com.ycw.grpc.MailboxProto value) {
      if (mailboxProtoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMailboxProtoIsMutable();
        mailboxProto_.add(value);
        onChanged();
      } else {
        mailboxProtoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .MailboxProto mailboxProto = 1;</code>
     */
    public Builder addMailboxProto(
        int index, com.ycw.grpc.MailboxProto value) {
      if (mailboxProtoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMailboxProtoIsMutable();
        mailboxProto_.add(index, value);
        onChanged();
      } else {
        mailboxProtoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MailboxProto mailboxProto = 1;</code>
     */
    public Builder addMailboxProto(
        com.ycw.grpc.MailboxProto.Builder builderForValue) {
      if (mailboxProtoBuilder_ == null) {
        ensureMailboxProtoIsMutable();
        mailboxProto_.add(builderForValue.build());
        onChanged();
      } else {
        mailboxProtoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MailboxProto mailboxProto = 1;</code>
     */
    public Builder addMailboxProto(
        int index, com.ycw.grpc.MailboxProto.Builder builderForValue) {
      if (mailboxProtoBuilder_ == null) {
        ensureMailboxProtoIsMutable();
        mailboxProto_.add(index, builderForValue.build());
        onChanged();
      } else {
        mailboxProtoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MailboxProto mailboxProto = 1;</code>
     */
    public Builder addAllMailboxProto(
        java.lang.Iterable<? extends com.ycw.grpc.MailboxProto> values) {
      if (mailboxProtoBuilder_ == null) {
        ensureMailboxProtoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, mailboxProto_);
        onChanged();
      } else {
        mailboxProtoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .MailboxProto mailboxProto = 1;</code>
     */
    public Builder clearMailboxProto() {
      if (mailboxProtoBuilder_ == null) {
        mailboxProto_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        mailboxProtoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .MailboxProto mailboxProto = 1;</code>
     */
    public Builder removeMailboxProto(int index) {
      if (mailboxProtoBuilder_ == null) {
        ensureMailboxProtoIsMutable();
        mailboxProto_.remove(index);
        onChanged();
      } else {
        mailboxProtoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .MailboxProto mailboxProto = 1;</code>
     */
    public com.ycw.grpc.MailboxProto.Builder getMailboxProtoBuilder(
        int index) {
      return getMailboxProtoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .MailboxProto mailboxProto = 1;</code>
     */
    public com.ycw.grpc.MailboxProtoOrBuilder getMailboxProtoOrBuilder(
        int index) {
      if (mailboxProtoBuilder_ == null) {
        return mailboxProto_.get(index);  } else {
        return mailboxProtoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .MailboxProto mailboxProto = 1;</code>
     */
    public java.util.List<? extends com.ycw.grpc.MailboxProtoOrBuilder> 
         getMailboxProtoOrBuilderList() {
      if (mailboxProtoBuilder_ != null) {
        return mailboxProtoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(mailboxProto_);
      }
    }
    /**
     * <code>repeated .MailboxProto mailboxProto = 1;</code>
     */
    public com.ycw.grpc.MailboxProto.Builder addMailboxProtoBuilder() {
      return getMailboxProtoFieldBuilder().addBuilder(
          com.ycw.grpc.MailboxProto.getDefaultInstance());
    }
    /**
     * <code>repeated .MailboxProto mailboxProto = 1;</code>
     */
    public com.ycw.grpc.MailboxProto.Builder addMailboxProtoBuilder(
        int index) {
      return getMailboxProtoFieldBuilder().addBuilder(
          index, com.ycw.grpc.MailboxProto.getDefaultInstance());
    }
    /**
     * <code>repeated .MailboxProto mailboxProto = 1;</code>
     */
    public java.util.List<com.ycw.grpc.MailboxProto.Builder> 
         getMailboxProtoBuilderList() {
      return getMailboxProtoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ycw.grpc.MailboxProto, com.ycw.grpc.MailboxProto.Builder, com.ycw.grpc.MailboxProtoOrBuilder> 
        getMailboxProtoFieldBuilder() {
      if (mailboxProtoBuilder_ == null) {
        mailboxProtoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ycw.grpc.MailboxProto, com.ycw.grpc.MailboxProto.Builder, com.ycw.grpc.MailboxProtoOrBuilder>(
                mailboxProto_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        mailboxProto_ = null;
      }
      return mailboxProtoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SendRequest)
  }

  // @@protoc_insertion_point(class_scope:SendRequest)
  private static final com.ycw.grpc.SendRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ycw.grpc.SendRequest();
  }

  public static com.ycw.grpc.SendRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SendRequest>
      PARSER = new com.google.protobuf.AbstractParser<SendRequest>() {
    @java.lang.Override
    public SendRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SendRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SendRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SendRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ycw.grpc.SendRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

