// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mailbox.proto

package com.ycw.grpc;

public interface SendResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SendResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 sendSuccess = 1;</code>
   * @return The sendSuccess.
   */
  long getSendSuccess();
}
