// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mailbox.proto

package com.ycw.grpc;

public interface StatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .MailboxProto mailboxProto = 1;</code>
   */
  java.util.List<com.ycw.grpc.MailboxProto> 
      getMailboxProtoList();
  /**
   * <code>repeated .MailboxProto mailboxProto = 1;</code>
   */
  com.ycw.grpc.MailboxProto getMailboxProto(int index);
  /**
   * <code>repeated .MailboxProto mailboxProto = 1;</code>
   */
  int getMailboxProtoCount();
  /**
   * <code>repeated .MailboxProto mailboxProto = 1;</code>
   */
  java.util.List<? extends com.ycw.grpc.MailboxProtoOrBuilder> 
      getMailboxProtoOrBuilderList();
  /**
   * <code>repeated .MailboxProto mailboxProto = 1;</code>
   */
  com.ycw.grpc.MailboxProtoOrBuilder getMailboxProtoOrBuilder(
      int index);
}
