// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mailbox.proto

package com.ycw.grpc;

public interface StatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();
}
