on:
  push:
    branches:
      - master
      - feature/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Cache Maven Repos
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Maven Clean And Install
        run: |
          mvn clean
          mvn install -DskipTests=true && mvn package -DskipTests=true
          echo '=====打包成功====='  

      - name: Build Docker Images
        run: |
          echo '=====开始构建cloud-gateway镜像====='
          cd cloud-gateway
          mvn docker:build
          cd ..
          
          echo '=====开始构建cloud-lobby镜像====='
          cd cloud-app/cloud-lobby
          mvn docker:build
          cd ../..
          
          echo '=====开始构建cloud-auth镜像====='
          cd cloud-auth
          mvn docker:build
          cd ..
          
          echo '=====构建成功=====' 

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Images tag and push
        run: |
          docker tag cloud-gateway:latest yangcaiwang/cloud-gateway:latest
          docker push yangcaiwang/cloud-gateway:latest
          
          docker tag cloud-lobby:latest yangcaiwang/cloud-lobby:latest
          docker push yangcaiwang/cloud-lobby:latest
          
          docker tag cloud-auth:latest yangcaiwang/cloud-auth:latest
          docker push yangcaiwang/cloud-auth:latest 

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: deploy by shh
        env:
          PROJECTS: "cloud-gateway;9000,cloud-lobby;9001,cloud-auth;9002"
          TAG: latest
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /opt/cloud-game
            chmod +x deploy.sh
            ./deploy.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }} ${PROJECTS} ${TAG}
            echo '执行完成'