name: Build and Deploy

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'


      - name: Maven Clean And Install
        run: |
          mvn clean
          mvn install -DskipTests=true && mvn package -DskipTests=true
          echo '=====打包成功====='  

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DEST_USERNAME }}
          password: ${{ secrets.DEST_TOKEN }}

      - name: Build Java Docker Images and push
        run: |
          echo '=====开始构建cloud-gateway镜像====='
          cd cloud-gateway
          mvn docker:build
          docker push ${{ secrets.DEST_USERNAME }}/cloud-game-grpc/cloud-gateway:${IMAGE_TAG}
          cd ..
          
          echo '=====开始构建cloud-app镜像====='
          cd cloud-business/cloud-app
          mvn docker:build
          docker push ${{ secrets.DEST_USERNAME }}/cloud-game-grpc/cloud-app:${IMAGE_TAG}  
          cd ..
          
          echo '=====推送成功=====' 


   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
