name: Build and Deploy

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Login docker-hub
        run:
          docker login -u yangcaiwang
          ycw123129 
          echo '=====登陆成功====='

      - name: Maven Clean Install
        run: |
          echo '=====开始mvn clean====='
          mvn clean
          
          echo '=====开始mvn install&&package====='
          mvn install -DskipTests=true && mvn package -DskipTests=true


      - name: Build Java Docker Images and push
        env:
          IMAGE_TAG: latest
        run: | 
          echo '=====开始构建镜像====='
          echo '=====开始构建cloud-gateway====='
          cd cloud-gateway
          mvn docker:build
          docker push cloud-game-grpc/cloud-gateway:${IMAGE_TAG}
          cd ..
          
          echo '=====开始构建cloud-app====='
          cd cloud-app
          mvn docker:build
          docker push cloud-game-grpc/cloud-app:${IMAGE_TAG}   
          cd ..
          
          echo '=====结束====='


   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
