name: Build and Deploy

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        run:
          echo '=====检出成功====='

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
        run:
          echo '=====设置成功====='

      - name: Maven Clean Install
        run: |
          echo '=====开始mvn clean====='
          mvn clean
          
          echo '=====开始mvn install&&package====='
          mvn install -DskipTests=true && mvn package -DskipTests=true
          
          echo '=====打包成功====='  

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DEST_USERNAME }}
          password: ${{ secrets.DEST_TOKEN }}
        run:
          echo '=====登陆成功====='

      - name: Build Java Docker Images and push
        run: |
          echo '=====开始构建镜像====='
          echo '=====开始构建cloud-gateway====='
          cd cloud-gateway
          mvn docker:build
          docker push ${{ secrets.DEST_USERNAME }}/cloud-game-grpc/cloud-gateway:${IMAGE_TAG}
          cd ..
          
          echo '=====上传成功=====' 
          
          echo '=====开始构建cloud-app====='
          cd cloud-business/cloud-app
          mvn docker:build
          docker push ${{ secrets.DEST_USERNAME }}/cloud-game-grpc/cloud-app:${IMAGE_TAG}  
          cd ..
          
          echo '=====上传成功=====' 
          
          echo '=====CI 结束====='


   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
